import 'package:hive/hive.dart';

part 'game_stat_model.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class GameStatModel extends HiveObject {
  @HiveField(0)
  final String gameName;

  @HiveField(1)
  final int score;

  @HiveField(2)
  final int tries;

  @HiveField(3)
  final DateTime timestamp;

  GameStatModel({
    required this.gameName,
    required this.score,
    required this.tries,
    required this.timestamp,
  });

  @override
  String toString() {
    return 'GameStat(game: $gameName, score: $score, tries: $tries, time: $timestamp)';
  }
}
