// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zRI7W09yAXq-GHApwALQZcfmbdcwe_Q',
    appId: '1:1009115010588:web:2c922ec6a3aa4b080cf1d9',
    messagingSenderId: '1009115010588',
    projectId: 'skinnovativelabs',
    authDomain: 'skinnovativelabs.firebaseapp.com',
    storageBucket: 'skinnovativelabs.firebasestorage.app',
    measurementId: 'G-FF8YYFE24M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpDplkmK7VSmuwjrq1lUahfiPQtgurpI',
    appId: '1:1009115010588:android:731f6fecca2c67170cf1d9',
    messagingSenderId: '1009115010588',
    projectId: 'skinnovativelabs',
    storageBucket: 'skinnovativelabs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQq4vKvMHM8As8jpo2igcI6nP4INC-coU',
    appId: '1:1009115010588:ios:af007a31a172c9070cf1d9',
    messagingSenderId: '1009115010588',
    projectId: 'skinnovativelabs',
    storageBucket: 'skinnovativelabs.firebasestorage.app',
    iosBundleId: 'com.karanjit.group.cogniBoost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQq4vKvMHM8As8jpo2igcI6nP4INC-coU',
    appId: '1:1009115010588:ios:f6359d67870445750cf1d9',
    messagingSenderId: '1009115010588',
    projectId: 'skinnovativelabs',
    storageBucket: 'skinnovativelabs.firebasestorage.app',
    iosBundleId: 'com.example.cogniBoost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4zRI7W09yAXq-GHApwALQZcfmbdcwe_Q',
    appId: '1:1009115010588:web:a0362c7383f73fb50cf1d9',
    messagingSenderId: '1009115010588',
    projectId: 'skinnovativelabs',
    authDomain: 'skinnovativelabs.firebaseapp.com',
    storageBucket: 'skinnovativelabs.firebasestorage.app',
    measurementId: 'G-FJYZ1T9631',
  );

}